# 启用自动更新
auto-update: false

balance-options:

  # 设置奇点消耗材料的倍数
  singularity-cost-multiplier: 1.0

  # 允许装备材质转换器更改 Slimefun 中装备的材质。
  # 钻石装备可升级为下界合金，但部分附属插件的物品可能在升级后无法使用
  # 请谨慎开启该选项！！
  allow-sf-item-transform: true

  # 是否启用无尽科技物品的研究
  # 开启后玩家需要消耗等级来解锁物品（与Slimefun设置一致）
  enable-researches: true

# 生物模拟相关设置
mob-simulation-options:

  # 每隔多少粘液刻输出产物和经验
  # 在没有更改 Slimefun 设置的情况下，1 粘液刻 = 0.5 秒
  ticks-per-output: 40

  # 设置从生物模拟中获取经验的倍率
  xp-multiplier: 1.0

# 矿机相关设置
quarry-options:

  # 每次生成矿物时, 生产加速器激活的概率 (范围: 0~1)
  oscillators:
    lapis: .5
    diamond: .5
    redstone: .5
    quartz: .5
    emerald: .5

  # 每隔多少粘液刻输出产物
    #  # 在没有更改 Slimefun 设置的情况下，1 粘液刻 = 0.5 秒
  ticks-per-output: 20

  # 允许在非下界的矿机输出下界产物（石英，下界岩，下界合金）
  output-nether-materials-in-overworld: false

  # 允许矿机输出哪些资源
  resources:

    coal: true
    iron: true
    gold: true
    lapis: true
    # 原版铜 (1.17+)
    copper: true
    quartz: true
    diamond: true
    emerald: true
    redstone: true
    netherite: true
    netherrack: true

# 设置高级铁砧的附魔等级上限
advanced-anvil-max-levels:
  sharpness: 9
  bane-of-arthropods: 9
  smite: 9
  protection: 10
  fortune: 6
  efficiency: 7
  fire-aspect: 6
  power: 7
  thorns: 13
  looting: 6
  unbreaking: 13

# 设置无尽套装的附魔等级，不会影响到已合成的无尽套装
# 在这里添加其他附魔没有任何效果，你只能更改已有附魔的等级
# 所有防具的保护等级加起来如果超过20级，则只按照20级来计算
infinity-enchant-levels:
  blade:
    unbreakable: false
    sharpness: 30
    smite : 30
    bane of arthropods : 30
    sweeping-edge : 30
    looting: 30
    fire-aspect: 30
  pickaxe:
    unbreakable: false
    efficiency: 50
    fortune: 30
    unbreaking : 15
  shovel:
    unbreakable: false
    efficiency: 50
    fortune: 30
    unbreaking : 15
  axe:
    unbreakable: false
    efficiency: 50
    fortune: 30
    unbreaking : 15
  bow:
    unbreakable: false
    power: 25
    flame: 30
    infinity: 30
    punch: 0
  crown:
    unbreakable: false
    protection: 20
    aqua-affinity: 10
    thorns: 20
  chestplate:
    unbreakable: false
    protection: 20
    thorns: 20
  leggings:
    unbreakable: false
    protection: 20
    thorns: 20
  boots:
    unbreakable: false
    protection: 20
    feather-falling: 0
    thorns: 20
  shield:
    unbreakable: false
    protection: 20
    thorns: 30
